### ISSUE TITLE
Installation issues over PIP

### ISSUE THREAD

**Issue by CharlieFuu69** [LittleChungi/PyCriCodecs#4]
Hello! I've had problems trying to install the WHL package via pip. It seems to be some kind of incompatibility:
`ERROR: PyCriCodecs-0.2.0-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.`

The install command is:
`pip install PyCriCodecs-0.2.0-cp39-cp39-win_amd64.whl`

My current version of pip and python is as follows:
`pip 22.2.2 from C:\Users\[MY_USER]\AppData\My_Programs\Python\lib\site-packages\pip (python 3.10)`

My platform architecture is 64-bit and OS is Windows 11.

I also tried downloading the code from the repository, but I get an error asking to install "Microsoft Visual C++ 14.0 (or later)".
What am I doing wrong?

**Comment by Youjose** [comment]
What Python version do you have? I ran this on Python 3.9, as indicated by `cp93` i.e Cpython version 3.9, I do run this on windows 10, but check on your Python version. And update it if needed.

If that still does not fix it somehow, try building the code from repository with after downloading the code, then in the directory with setup.py, run the command `python setup.py install`

Tell me how it goes and if it works or not, I will try researching more into this if it didn't.

**Comment by CharlieFuu69** [comment]
Thanks for answering =D
I'm running Python v3.10.4 (visible in the version line returned by `pip -V`).
As for building the code, I have installed Visual Studio Build Tools but no success:
![Captura de pantalla (679)](https://user-images.githubusercontent.com/77955772/193501577-3f809f9d-c412-4160-b3f8-8d2b01e6d43b.png)

I have installed "Microsoft Visual C++" later than v14.0 and still I have not succeeded:
![image](https://user-images.githubusercontent.com/77955772/193501938-68ee1ba8-2469-4e4a-9e05-f67a80c368e0.png)

2 options: It is a strange situation, or I have skipped a step XD

**Comment by Youjose** [comment]
Hmm, I've got some tips here, maybe setup tools is outdated, so try `pip install --upgrade setuptools`, first.

and also check the compilers in https://wiki.python.org/moin/WindowsCompilers.

Here I also provided a new wheel file, this one might work as I compiled it with `python setup.py bdist_wheel --universal`, added the Universal tag if it might have any help there, so tell me how it goes!
[PyCriCodecs-0.2.1-cp39-cp39-win_amd64.zip](https://github.com/LittleChungi/PyCriCodecs/files/9694841/PyCriCodecs-0.2.1-cp39-cp39-win_amd64.zip)

**Comment by CharlieFuu69** [comment]
Unfortunately it doesn't seem to work for me. I get the exact same thing when trying to install with pip.
I've run the `pip debug --verbose` command, and got the following entries that may be helpful:
```
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.5
  distlib==0.3.5
  distro==1.7.0
  msgpack==1.0.4
  packaging==21.3
  pep517==0.12.0
  platformdirs==2.5.2
  pyparsing==3.0.9
  requests==2.28.1
  certifi==2022.06.15
  chardet==5.0.0
  idna==3.3
  urllib3==1.26.10
  rich==12.5.1 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.12.0
  typing_extensions==4.3.0 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.8.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 36
  cp310-cp310-win_amd64
  cp310-abi3-win_amd64
  cp310-none-win_amd64
  cp39-abi3-win_amd64
  cp38-abi3-win_amd64
  cp37-abi3-win_amd64
  cp36-abi3-win_amd64
  cp35-abi3-win_amd64
  cp34-abi3-win_amd64
  cp33-abi3-win_amd64
  cp32-abi3-win_amd64
  py310-none-win_amd64
  py3-none-win_amd64
  py39-none-win_amd64
  py38-none-win_amd64
  py37-none-win_amd64
  py36-none-win_amd64
  py35-none-win_amd64
  py34-none-win_amd64
  py33-none-win_amd64
  py32-none-win_amd64
  py31-none-win_amd64
  py30-none-win_amd64
  cp310-none-any
  py310-none-any
  py3-none-any
  py39-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any
```
I have a feeling the error is related to this list...

**Comment by Youjose** [comment]
Ok, after hours of research, it's just a compatibility issue.
Your python for some reason is not compatible with Cpython 3.9, so I just installed python 3.10.4 and built the wheel file for your version. Hope this one works. If it did not, than that means you probably need to solve the issue with the C++ compiler/build tools to build. Tell me how this one pans out.
[PyCriCodecs-0.2.1-cp310-cp310-win_amd64.zip](https://github.com/LittleChungi/PyCriCodecs/files/9696783/PyCriCodecs-0.2.1-cp310-cp310-win_amd64.zip)

**Comment by CharlieFuu69** [comment]
GGs. 
![image](https://user-images.githubusercontent.com/77955772/193572617-c6645178-36eb-44e4-90dc-140cd5d1e739.png)

Thank you for assisting me with this problem. This library seemed pretty good to me and I wanted to test it to see if it is possible to integrate it into a Ren'Py game. Now that will be my way to go.

Really, thanks for everything. I will mark this issue as closed =D
