### ISSUE TITLE
Readme says usmObj should have a method called parse when it does not

### ISSUE THREAD

**Issue by ItsCharaHere** [LittleChungi/PyCriCodecs#7]
there is also a similar method called build, but when using that and then calling get_usm nothing seems to happen

**Comment by Youjose** [comment]
Hello, thanks for reporting and yeah, I think I used to called it `parse` before I changed it to `build`, and forgot to update the Readme. I think there are probably similar cases with the other formats where I forgot to change the readme, will need to fins those later.

> but when using that and then calling get_usm nothing seems to happen

This sounds like PyCriCodecs is just crashing, although generally the code is just awful and written badly as I was learning. Definitely needs a rewrite as it stands, but you can open explain this issue in more details and I will try to look at it.

**Comment by Youjose** [comment]
I am closing this due no response back from the issue opener, get_usm() works for me when done correctly, and  the typo in question has been fixed. I might rewrite the USM class one day but for now it will stay as is.
