### ISSUE TITLE
trouble with a .awb file 

### ISSUE THREAD

**Issue by GoldieLeGenie** [LittleChungi/PyCriCodecs#8]
Hi, great job! I just have a small issue with an AWB file that cannot be decrypted correctly. Do you have a solution for this file It would be really awesome ? https://www.mediafire.com/file/7tefsy31qy3wiqq/voice_r01.awb/file

**Comment by Youjose** [comment]
Hello, HCA files are encrypted using a key, and you would need this key to decrypt it, I searched a bit and managed to find that this AWB is from a game called "One Piece Treasure Cruise", and the key they use is `1224` or `0x04C8`, with this information you can extract the audio by running this:
```python
from PyCriCodecs import *
awbobj = AWB("voice_r01.awb") # Given that the this script is in the same folder with the file.
awbobj.extract(True, 1224)
```
This will extract the awb. Better yet, if you have an ACB that is with this AWB you can get the original filename of the audio, but currently my library does not support that, so I would suggest using a better tool called [VGMStream](https://github.com/vgmstream/vgmstream/releases/tag/r1866), it also can extract this awb with no problems!

Hope this helps, tell me how it goes.

**Comment by GoldieLeGenie** [comment]
Yep, it was from 'One Piece Treasure Cruise,' and the code you gave me works perfectly fine. Thank you so much! Have a great day :)
